### ISSUE TITLE
Error on updating forecast

### ISSUE THREAD

**Issue by nurbietis** [SalesforceLabs/QuotaEdit#76]
Hi there,

the app worked fine up until recently when started getting this error:
Upsert failed. First exception on row 0; first error: INVALID_OPERATION, Use the current API version when inserting, updating, or deleting a quota value. Some features aren’t available in earlier API versions: []
Is it possible to update API version from my side?

Regards,
Nerijus

**Comment by alonkama** [comment]
I updated the app to use the latest API version. Please try retrieving v2.5 and trying again. 

This is probably related to Scheduled Date Forecasting, which is not officially supported. Nevertheless, I encourage you to try with the latest version.

**Comment by nurbietis** [comment]
Thank you very much for updating app.
I tried to update it through AppExchange Get It Now > Open Login Screen and I get this error:
<img width="1480" alt="screen shot 2018-07-11 at 22 39 39" src="https://user-images.githubusercontent.com/37210686/42600842-b4482b94-855b-11e8-8ce1-06bcab4ae840.png">
Any ideas?

**Comment by alonkama** [comment]
I just tested it on a couple of accounts and it worked fine.
I would try again, maybe from a different browser?

**Comment by nurbietis** [comment]
Yes changing browser worked.
Thank you for that!
