### ISSUE TITLE
Copy Quota to another period does not work for Quarterly Forecasting

### ISSUE THREAD

**Issue by morangela** [SalesforceLabs/QuotaEdit#77]
Created quotas for period FQ3 FY 2018.
When trying to copy quotas to another period, only monthly options are available.

Thanks,
Angela
[quota issue.pdf](https://github.com/SalesforceLabs/QuotaEdit/files/2176910/quota.issue.pdf)

**Comment by alonkama** [comment]
I see that the radio button on top says "Month" but the dropdown is for quarters. Strange. Sometimes I've seen superfluous Forecast Periods created by Forecasting, which makes it ambiguous to the Edit Quotas tool.

The quota is set based on the start month of the period, regardless of whether it's Quarter or Month. Could you try copy quota for the start month of your intended period? Then see if it was applied correctly.

**Comment by morangela** [comment]
Thanks for that...I tried it and it worked.
