### ISSUE TITLE
Quota related field does not appear in User set up

### ISSUE THREAD

**Issue by mcabraal** [SalesforceLabs/QuotaEdit#80]
I have installed the Collaborative Forecasting Edit Quotas app and went through the full process as listed below, but my manager and I cannot see the "Quotas" related field under the User in Setup. 

https://resources.docs.salesforce.com/latest/latest/en-us/sfdc/pdf/forecasts.pdf

**Comment by alonkama** [comment]
There is no "Quotas" related field under the User in Setup. Quotas can be
seen on the Collaborative Forecasts page. See
https://help.salesforce.com/articleView?id=forecasts3_showing_hiding_quotas.htm&type=5
It is unrelated to the Edit Quotas app. That app is used only to
insert/update Quotas.

**Comment by mcabraal** [comment]
Thank you Alonkama. It is helpful to see the quotas but I need to input and edit quotas first. My users do not currently have quotas inserted in the system. How do I insert quotas?

**Comment by alonkama** [comment]
Inserting quotas is exactly what this app is for. Please follow the
installation instructions and ensure that the permission set is assigned:
https://help.salesforce.com/articleView?id=forecasts3_showing_hiding_quotas.htm&type=5
If it's assigned to you, then you should be able to find the Edit Quotas
app in the navigation bar. From there you should be able to insert quotas
for your forecasting users.

**Comment by mcabraal** [comment]
Thank you - Do you have a link to instructions on how to insert quotas using the app? I found this one - https://help.salesforce.com/articleView?id=forecasts3_loading_quota_data.htm&type=5, but is there a way to insert quotas manually without using data loader or API?

**Comment by alonkama** [comment]
Hi,

Edit Quotas is an AppExchange app, meaning that it's not officially
supported by Salesforce. The only documentation for it is at
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3000000B41EqEAJ
and at https://github.com/SalesforceLabs/QuotaEdit . It should be an
intuitive UI, assuming that you're able to bring it up.

**Comment by mcabraal** [comment]
Thank you Alon. I was able to upload all quotas very easily using data loader so that issue is resolved. My question now is - I would like to report on the "Closed" and "Commit" forecast category percentages that are shown in Forecasts, per user. 

I created a custom report type for Forecast Items and Quotas, but neither of these options can pull up the "Closed" and "Commit" fields. Do you have any other ideas?

**Comment by alonkama** [comment]
That's described on page 25 of the doc that you originally linked: https://resources.docs.salesforce.com/latest/latest/en-us/sfdc/pdf/forecasts.pdf
If you have more questions on Forecasting, but that are not related to the Edit Quotas app, I encourage you to file a Support ticket or check out the Success Community. There are lots of resources there.
