### ISSUE TITLE
Can you offer other type of quotas?

### ISSUE THREAD

**Issue by monicajgkr** [SalesforceLabs/QuotaEdit#85]
Hi, 

I am wondering if you guys have something available to make it possible to save and track other types of targets, I am specifically interested in SDR targets based on the number of opportunities created. 

So the actual number of different opportunities related to a specific Salesforce user, not the revenue or quantity of the opportunities.

Is it possible to somehow do this with your current app or do you have something similar we can use?

Please let me know if you need any additional information.

Thanks in advance,

**Comment by alonkama** [comment]
This package is deprecated, since Collaborative Forecasts supports quota edits directly in Lightning. 

Quotas are only available for Forecasting - no other entity.
