### ISSUE TITLE
quotas not adding up properly for the whole team including manager

### ISSUE THREAD

**Issue by Rociosalesforce** [SalesforceLabs/QuotaEdit#86]
Hello, we are using the forecast for one team together as the same time, and the amount of the forecast of the manager is not adding up to the team, so the total amount is not reflecting correctly. Quota for a manager should reflect his own quota plus his team.

**Comment by alonkama** [comment]
Please see Salesforce Help & Training site, or file a support ticket. I don't believe this is an issue with this app.
